---
- name: Ensure Ubuntu Distro is Supported
  get_url:
    url='https://deb.nodesource.com/node/dists/{% verbatim %}{{ ansible_distribution_release }}{% endverbatim %}/Release'
    dest=/dev/null
  register: distrosupported

- name: Remove Old Chris Lea PPA
  apt_repository:
    repo='ppa:chris-lea/node.js'
    state=absent
  when: distrosupported|success

- name: Remove Old Chris Lea Sources
  file:
    path='/etc/apt/sources.list.d/chris-lea-node_js-{% verbatim %}{{ ansible_distribution_release }}{% endverbatim %}.list'
    state=absent
  when: distrosupported|success

- name: Add Nodesource Keys
  apt_key:
    url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state=present

- name: Add Nodesource Apt Sources List Deb
  apt_repository:
    repo='deb https://deb.nodesource.com/node {% verbatim %}{{ ansible_distribution_release }}{% endverbatim %} main'
    state=present
  when: distrosupported|success

- name: Add Nodesource Apt Sources List Deb Src
  apt_repository:
    repo='deb-src https://deb.nodesource.com/node {% verbatim %}{{ ansible_distribution_release }}{% endverbatim %} main'
    state=present
  when: distrosupported|success

- name: Install NodeJS
  apt: pkg=nodejs state=latest update_cache=true
  when: distrosupported|success
  register: nodejsinstalled

- include: taskrunner.yml
  when nodejsinstalled|success
